---
- name: Bash Install
  hosts: localhost
  connection: local

  # gather machine informations
  gather_facts: yes

  # Enable root previlegies
  become: yes

  # Run suitable scripts
  tasks:

    - name: Install bash
      package:
        name:
          - bash

- name: Bash Config
  hosts: localhost
  connection: local

  # gather machine informations
  gather_facts: yes

  # Enable user previlegies
  become: yes
  become_user: "{{ ansible_facts.env.SUDO_USER }}"

  # Run suitable scripts
  tasks:

    - name: Copy Bashrc
      copy:
        src: templates/bashrc.j2
        dest: "{{ ansible_env.HOME }}/.bashrc"
    
    - name: Copy Bash Aliases
      copy:
        src: templates/bash_aliases.j2
        dest: "{{ ansible_env.HOME }}/.bash_aliases"
