---
- name: Run Desktop Bootstrap
  hosts: localhost
  connection: local

  # gather machine informations
  gather_facts: no

  # Enable root previlegies
  become: No

  # Run suitable scripts
  tasks:

  - name: System
    debug:
      msg:
        - Start desktop configuration
  
- name: Start bootstrap.yml
  import_playbook: playbooks/bootstrap.yml
