---
- name: Fedora Bootstrap
  hosts: localhost
  connection: local

  # gather machine informations
  gather_facts: yes

  # Enable root previlegies
  become: no

  # Run suitable scripts
  tasks:

  - name: Fedora
    debug:
      msg:
        - Operating System{{':'}} {{ ansible_distribution }}
