---
- name: Git
  hosts: localhost
  connection: local

  # gather machine informations
  gather_facts: yes

  # Enable root previlegies
  become: yes

  # Run suitable scripts
  tasks:

    - name: install git
      package:
        name:
          - git
